### ISSUE TITLE
Incorrect main class causes a crash

### ISSUE THREAD

**Issue by huntc** [huntc/landlord#26]
When an incorrect main class is specified, Landlord crashes.

Landlord shouldn’t crash.

**Comment by longshorej** [comment]
Hrm - I'm not observing this. Perhaps we can dig in at today's standup.

Note there is still one remaining issue that has to do with programs that call `System.exit` where it can kill the JVM if the `SecurityManager` was destroyed. I'm hoping to understand that better today and get it fixed.

```bash
~/work/farmco/landlord/landlord#detached* $ cargo run -- -cp ../landlordd/test/target/scala-2.12/classes example.DoesntExist
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/landlord -cp ../landlordd/test/target/scala-2.12/classes example.DoesntExist`
java.lang.ClassNotFoundException: example.DoesntExist-> 1
```

**Comment by huntc** [comment]
Here's a possibly related cause:

```
Uncaught error from thread [landlordd-akka.actor.default-dispatcher-2]: example/Hello has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[landlordd]
java.lang.UnsupportedClassVersionError: example/Hello has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.huntc.landlord.JvmExecutor$$anonfun$starting$1.applyOrElse(JvmExecutor.scala:207)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at com.github.huntc.landlord.JvmExecutor.akka$actor$Timers$$super$aroundReceive(JvmExecutor.scala:121)
	at akka.actor.Timers.aroundReceive(Timers.scala:52)
	at akka.actor.Timers.aroundReceive$(Timers.scala:38)
	at com.github.huntc.landlord.JvmExecutor.aroundReceive(JvmExecutor.scala:121)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
